
[install]
allowed_installtypes = ["wholedisk"]
copy_mode = "bootc"
bootc_imgref = "containers-storage:ghcr.io/why-context/inver:latest"
bootc_target_imgref = "ghcr.io/why-context/inver:latest"

[distro]
name = "Inver"

[[bento]]
title = "Welcome to Inver"
desc = "A minimal immutable operating system for gamers."
link = "https://github.com/why-context/inver"
icon = "explore-symbolic"

[[bento]]
title = "Get help"
desc = "Open an issue on the repo"
link = "https://github.com/why-context/inver/issues"
icon = "chat-symbolic"

[[bento]]
title = "Contribute"
desc = "Source and build files"
link = "https://github.com/why-context/inver"
icon = "applications-development-symbolic"

[[postinstall]]
module = "GRUB2"

[[postinstall]]
module = "EfiStub"
distro_name = "Inver"

[[postinstall]]
module = "Dracut"

[[postinstall]]
module = "SELinux"

[[postinstall]]
module = "Language"
lang = "en"
